### ISSUE TITLE
Used In info is not displayed if an image is added to a content from Old Media Gallery. (Untill content syncronization)

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1808] opened 2020-09-04 11:52 UTC
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Old Media Gallery enabled in Stores -> Configuration -> Advanced-> System -> Media Gallery -> Enable Old Media Gallery - Yes
![old_med_gal_yes](https://user-images.githubusercontent.com/45624059/92234637-106b8b80-eebb-11ea-8ec1-b22395a8d79a.png)

### Steps to reproduce (*)
1. Go to **Catalog** - **Categories**.
2. Expand **Content** and click **Select From Media Gallery**
Verify that _Old Media Gallery_ is opened 
3. Click **Search Adobe Stock**, select any image and **Save Preview**. **Confirm**
the Previously saved image appeared in the _Old Media Gallery_ and is selected
4. Click **Add Selected** button
5. The image has been added to the Category. **Save** category
6. Go to _Stores -> Configuration -> Advanced-> System -> Media Gallery_, set _Enable Old Media Gallery_ - **No**
![old_med_gal_no](https://user-images.githubusercontent.com/45624059/92235377-3f363180-eebc-11ea-95a7-ce32ffa2ccc6.png)
7. **Save** configuration and clean Magento cache `bin/magento cache:clean`
8. Go to **Content - Media Gallery**, select the previously used image
9. Click "three dots" and select **View Details**
10. Observe the _Used In_ info

### Expected result (*)
The image is Used In Categories(1) should be displayed
![used_in_cat](https://user-images.githubusercontent.com/45624059/92236296-d059d800-eebd-11ea-9ef1-7d7ca1d89059.png)
 
### Actual result (*)
![nousedin](https://user-images.githubusercontent.com/45624059/92235911-25e1b500-eebd-11ea-8717-1ad3077a3cd9.png)

### Note
The Used in info will appear after running `bin/magento media-content-sync`

**Comment by sivaschenko** [comment] 2020-09-08 18:23
Cannot reproduce locally with launched:
`bin/magento queue:consumers:start media.gallery.synchronization`
`bin/magento queue:consumers:start media.content.synchronization`

**Comment by sivaschenko** [comment] 2020-09-08 18:56
Looks like we need to configure cloud to run consumers
https://devdocs.magento.com/guides/v2.4/config-guide/mq/manage-message-queues.html
https://devdocs.magento.com/cloud/env/variables-deploy.html#cron_consumers_runner

**Comment by sivaschenko** [comment] 2020-09-09 09:55
Cloud instance was configured to run consumers as part of `cron:run`.

Locally several executions of `bin/magento cron:run` are required after enabling media gallery to update the content links.
(can be checked in `queue_message` and `queue_message_status` tables - `4` is success status).

@chalov-anton can you please retest the issue on cloud and local environments using the instructions above

**Comment by engcom-Bravo** [comment] 2020-09-09 10:55
@sivaschenko Rechecked on the Claud instance with the updated configuration. The _Used In_ appeared in details page after some time.

**Comment by sivaschenko** [comment] 2020-09-09 12:55
Great, thank you!

**Closed as completed by sivaschenko** 2020-09-09 12:55 UTC
Labels: bug, Severity: S2
