### ISSUE TITLE
A small truncation of the "note symbol" in Adobe Stock filters

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#1398] opened 2020-05-29 13:27 UTC
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** click **Search Adobe Stock**
2. Click **Filters**
3. Observe the :grey_question: symbol for _Isolated Assets_ checkbox

### Expected result (*)
No truncation

### Actual result (*)
A small truncation at the top of the symbol
![truncation](https://user-images.githubusercontent.com/45624059/83264604-fbe76b00-a1c8-11ea-8b02-9d790dc7a2ed.png)

**Comment by konarshankar07** [comment] 2020-06-04 03:56
@magento I am working on this

**Comment by konarshankar07** [comment] 2020-06-04 04:08
Hello @chalov-anton ...
I'm not able to reproduce this issue in latest `2.0.0-stabilization` branch. Please check the below screenshot
![image](https://user-images.githubusercontent.com/39480008/83713956-15643900-a647-11ea-8f93-e4b5869c6a76.png)

**Comment by chalov-anton** [comment] 2020-06-04 12:39
Hello @konarshankar07 

Please, try to _Zoom_ in or out your browser. For example on my monitor, I can see the truncation at 90% and 100%

![1398_zoom](https://user-images.githubusercontent.com/45624059/83757721-976d5580-a679-11ea-885c-ac27a7b19799.png)

**Comment by konarshankar07** [comment] 2020-06-09 04:46
Hello @chalov-anton ...
Can you please specify the browser? because I checked in Chrome version 81.0.4044.113 and not able to find any issue with zoom 90%. Please check the below screenshot
![image](https://user-images.githubusercontent.com/39480008/84107019-4aeb9680-aa3a-11ea-9dc1-b41d8402c74e.png)

**Comment by chalov-anton** [comment] 2020-06-09 11:03
Hello @konarshankar07  
I'm using Chrome, Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by konarshankar07** [comment] 2020-06-11 04:54
Hello @chalov-anton ...
I have updated the chrome but still not able to reproduce this issue in the latest version. Please check the screenshot

![image](https://user-images.githubusercontent.com/39480008/84346357-6b982580-abcd-11ea-8763-9da7891e71a8.png)

Chrome Version
![image](https://user-images.githubusercontent.com/39480008/84346498-bb76ec80-abcd-11ea-81a9-dce3cb96cf17.png)

I'm checking on Ubuntu OS so what's your OS in which you are testing?

**Comment by chalov-anton** [comment] 2020-06-11 12:34
@konarshankar07 
I'm also using Ubuntu OS
Maybe it depends on the screen resolution. My screen resolution is 1920 x 1080 (16:9)

**Comment by konarshankar07** [comment] 2020-07-08 18:08
I'm unassigning this issue cause I'm not able to reproduce. I hope anyone else can reproduce this issue
Thanks

**Closed as completed** 2020-07-29 13:52 UTC
Labels: bug, Frontend/UI, Priority: P3, Severity: S4, Progress: done
