### ISSUE TITLE
Tags are not properly aligned

### ISSUE THREAD

**Issue by lenaorobei** [magento/adobe-stock-integration#1707] opened 2020-08-03 19:11 UTC
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
4. Uploaded image 

### Steps to reproduce (*)

1. Go to media gallery
2. Edit image details

### Expected result (*)

Delete icon is aligned with corresponding tag.

### Actual result (*)

<img width="1494" alt="Screen Shot 2020-08-03 at 2 08 20 PM" src="https://user-images.githubusercontent.com/17548019/89218101-0fc99780-d593-11ea-9115-1af3790589cc.png">

**Comment by joweecaquicla** [comment] 2020-08-04 08:05
@magento I am working on this

**Comment by chalov-anton** [comment] 2020-08-04 08:10
@lenaorobei 
I'm using Google Chrome browser on Ubuntu OS. The issue is not reproducible
![tags](https://user-images.githubusercontent.com/45624059/89269672-df413680-d642-11ea-8a08-f43de53b99f6.png)
I have also rechecked this on Internet Explorer browser on Windows OS. The issue is not reproducible

**Comment by sivaschenko** [comment] 2020-08-04 10:51
@lenaorobei I've seen this issue, it happened for me if the static content is not updated. Closing as not actual

**Closed as completed by sivaschenko** 2020-08-04 10:51 UTC
Labels: bug, Priority: P2, Severity: S2, Progress: done
