### ISSUE TITLE
Undefined index: media_gallery_asset when running bin/magento setup:upgrade

### ISSUE THREAD

**Issue by diazwatson** [magento/adobe-stock-integration#594] opened 2019-10-27 15:18 UTC
### Preconditions (*)

1. Magento version: dev-2.3-develop

### Steps to reproduce (*)

1. Setup your local env as described in the [Installation Guide](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)
2. Run `bin/magento setup upgrade`

### Expected result (*)

1. Command executes and installs/upgrades database tables

### Actual result (*)

1. 
```
Cache cleared successfully
Updating modules:
Schema creation/updates:
Notice: Undefined index: media_gallery_asset in /Users/rdiaz/Sites/adobestock/lib/internal/Magento/Framework/Setup/Declaration/Schema/Declaration/SchemaBuilder.php on line 352
```

**Comment by sivaschenko** [comment] 2019-10-27 16:52
Hi @diazwatson thanks for reporting this issue! Can you please check if it's actual for the latest codebase as it might have been fixed in https://github.com/magento/adobe-stock-integration/pull/590 (merged 7 hours ago)

**Comment by Nazar65** [comment] 2019-10-31 08:33
HI @diazwatson this is caused by new module added and you need to re symlink modules to vendor path, so then the new module will be available and have table media_gallery_asset

![DeepinScreenshot_select-area_20191031103247](https://user-images.githubusercontent.com/2481206/67931067-ceeabf80-fbc9-11e9-96cd-b14eae754ca5.png)

**Comment by sivaschenko** [comment] 2019-11-01 12:37
`AdobeMediaGallery` has been added to `module.xml` of `AdobeStockAsset`

**Closed as completed by sivaschenko** 2019-11-01 12:37 UTC
Labels: bug

**Comment by diazwatson** [comment] 2019-11-04 16:11
In case anyone has this issue, I have fixed by:
```
composer require magento/adobe-stock-integration
```
to create the new Symlinking from ./ext/magento/stock-integration/AdobeMediaGallery into vendor
```
bin/magento cache:clean
```
to clean cache
```
bin/magento setup:upgrade
```
to install the missing module

**Comment by MarcianoH** [comment] 2020-03-02 17:57
I've fixed this by manually removing the adobe_stock_asset table.
