### ISSUE TITLE
Login to Adobe Stock with Google open id fails

### ISSUE THREAD

**Issue by chalov-anton** [magento/adobe-stock-integration#802] opened 2019-11-28 14:45 UTC
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. **AdobeID which is connected to google account**
### Steps to reproduce (*)
1. Do **not** Sign In into Adobe Stock integration or into adobe.com in your web browser
2. From Magento Admin go to Content - Pages, click **Add New Page**
3. Expand **Content** Click **Show / Hide Editor**, select **Insert Image...**
4. Click **Search Adobe Stock**
5. Click **Sign In**
![sign_in_281119](https://user-images.githubusercontent.com/45624059/69813640-4298e000-11fb-11ea-93be-ca65f87b61f7.png)
6. In appeared _Sign in - Adobe ID_ window select **Continue with Google**
![Sign in - Adobe ID - authorization_g](https://user-images.githubusercontent.com/45624059/69813886-cbb01700-11fb-11ea-85c2-bc08aa62a02d.png)
### Expected result (*)
You are successfully Signed In
### Actual result (*)
_There was an error with this action. Try again later_ error appears
![Error29112019](https://user-images.githubusercontent.com/45624059/69814098-306b7180-11fc-11ea-99cb-b451317a846c.png)
If you are Signed In into adobe.com in your browser, there is no error after Sign In 
![Peek 2019-11-28 16-39](https://user-images.githubusercontent.com/45624059/69815034-28143600-11fe-11ea-904f-e97fc1f1ea2e.gif)

**Comment by sivaschenko** [comment] 2020-08-12 13:17
Looks like the issue is on IMS side and cannot be fixed on ASI side

**Closed as completed by sivaschenko** 2020-08-12 13:17 UTC
Labels: bug, Priority: P2, Severity: S2
