### ISSUE TITLE
[MFTF] User locates preview image in the Media Gallery

### ISSUE THREAD

**Issue by filmaj** [magento/adobe-stock-integration#446] opened 2019-09-23 13:31 UTC
# Description
Implement MFTF test to cover scenario: "User locates preview image in the Media Gallery" (story 27, #329)

#  Preconditions

1. Admin User is logged into Admin Panel
2. User signs into Adobe IMS

# Test steps

3. Open Adobe Stock Images Grid 
4. User expands image preview of first already-preview-saved image
5. User clicks ~View Preview~ Locate button in Media Gallery button
6. Verify that preview image is displayed in the Media Gallery

**Comment by drpayyne** [comment] 2019-11-05 06:28
@filmaj @sivaschenko, I understand the story is different, and functionality too. But I feel the test for this and https://github.com/magento/adobe-stock-integration/issues/444 is the same. Both would be testing the _Locate_ button. And this button is irrespective of whether an image is licensed or not. If there's a local copy of image (whether it's a preview or a fully sized licensed), _Locate_ button appears and I feel the logic of the test is identical. 

I've already created a PR for https://github.com/magento/adobe-stock-integration/issues/444 at https://github.com/magento/adobe-stock-integration/pull/639. Please refer the test and let me know.

Thanks.

**Comment by drpayyne** [comment] 2019-11-05 06:43
With the generous help of @sivaschenko, I have come to this understanding of which button appears when and with what text in the image preview section. Also linked the MFTF test issues. So from the below understanding, I feel this is a duplicate of #444.

New image #440(in Media Gallery), #442(with label in Stock Grid)
Preview button text: Save Preview
License button text: License and Save

Already saved preview #440(in Media Gallery), #442(with label in Stock Grid)
Preview button text: Locate
License button text: License and Save

Already licensed on adobe stock (not saved locally) #443
No grey button
License button text: Save

Already saved preview and licensed in Adobe Stock (no licensed image locally) #443
Preview button text: Locate
License button text: Save

Licensed image locally #444
Preview button text: Locate
No red button

**Comment by filmaj** [comment] 2019-11-05 15:54
Hey @drpayyne, sorry, I'm a bit confused. Given your breakdown above, seems like  there are several interactions at play and each changes the expected button text as well as which buttons are displayed. In that sense, I feel there is value in having separate tests for these various scenarios.

Or am I misunderstanding  you?

**Comment by drpayyne** [comment] 2019-11-05 18:49
@filmaj Yes, indeed. A separate test for each scenario would be better, in my opinion. At the moment, only #440 and #442 would need to have two tests each. Already developed two tests for #443 and created a PR.

But this issue is a duplicate of #444, don't you think? (test logic wise)

**Comment by sivaschenko** [comment] 2019-11-13 14:57
@drpayyne I don't think this is duplicate as the preconditions are different. It's just a very similar test in my opinion :)

**Closed as completed** 2019-11-20 22:01 UTC
Labels: MFTF tests
