### ISSUE TITLE
Pressing escape key confirms the save/license confirmation popup

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#572] opened 2019-10-23 22:50 UTC
### Preconditions
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> Advanced -> System -> Adobe Stock Integration fieldset

### Steps to reproduce
1. Login to admin panel
2. Open Magento Media Gallery (i.e. go to Cms -> Pages, edit the page and insert image)
3. Click "Search Adobe Stock" button to open images grid
4. Click on any image to expand image preview
5. Click on "Save Preview" button
6. Press "Escape" key on the keyboard

### Actual result
Image preview is saved

### Expected result
Popup should be closed and image should not be saved

**Comment by konarshankar07** [comment] 2019-10-24 18:46
Hello @sivaschenko ,
I think we need to fix this issue in Magento repo so that the future modal will not have this kind of issue
Let me know your thoughts.
Thanks

**Comment by sivaschenko** [comment] 2019-10-29 10:24
@konarshankar07 can you reproduce the same issue with any othe prompts in Magento Admin Panel?

**Comment by sivaschenko** [comment] 2020-03-18 17:11
Hi @konarshankar07 would you like to continue working on this issue and identify the backward compatible fix as the intial fix was not accepted to magento2?

**Comment by konarshankar07** [comment] 2020-03-18 18:11
Hello @sivaschenko ..
Yes, I will create another PR in magento repo for this issue ASAP
Thanks

**Comment by konarshankar07** [comment] 2020-03-21 04:16
Hello @sivaschenko ...
I think this issue has been fixed by someone. I'm not able to reproduce it in latest magento repo or Adobe Stock Integration repo. Please test and let me know if you are able reproduce it.
Thanks

**Comment by sivaschenko** [comment] 2020-03-21 13:30
Hi @konarshankar07 I believe it was fixed by you in https://github.com/magento/magento2/pull/25349

However, I am keeping this issue open due to comments in the pull request

**Comment by konarshankar07** [comment] 2020-03-21 13:39
Hello @sivaschenko ...
Yes, I know I have fixed this issue but my fix was reverted and then someone has fixed including BIC and I also checked the implementation and someone has fixed with different approach but not mine.
Thanks

**Comment by sivaschenko** [comment] 2020-03-22 12:43
Hi @konarshankar07 can you please add a link to commit or pull request of the latest fix for future reference

**Closed as completed** 2020-07-28 16:17 UTC
Labels: bug, Frontend/UI, Priority: P3, Severity: S2, Progress: done
